name: Java and Robot Tests

on:
  push:
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      neo4j:
        image: neo4j:4.4.23
        env:
          NEO4J_AUTH: neo4j/12345678
        ports:
          - "7474:7474"
          - "7687:7687"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "adopt"

      - name: Build Java application
        run: mvn compile

      - name: Run Java application
        run: mvn exec:java -Dexec.mainClass="main.App"&
      
      - name: Install Robot Framework
        run: |
          pip install robotframework
          pip install robotframework-requests
          pip install robotframework-sshlibrary

      - name: Run Robot Tests
        run: | 
          robot robot_tests/addActorTests.robot robot_tests/addMovieTests.robot robot_tests/addRelationshipTests.robot robot_tests/hasRelationshipTests.robot
          bash robot_tests/baconTestsDatabase.sh
          robot robot_tests/computeBaconPathTests.robot robot_tests/computeBaconNumberTests.robot
